### ISSUE TITLE
assets hash is colliding

### ISSUE THREAD

**Issue by MichaelKling** [MeiSign/yii-chartjs#1]
In /components/ChartJs.php @ line 39 the assets are published via:

``` php
$assetsUrl = Yii::app()->assetManager->publish($assetsPath, true, -1, $this->forceCopyAssets);
```

With the second parameter = true the hash for the assets directory name is only done one "assets", not on the full path. Unfortunatly this is the exact same call and setup like in the extension "bootstrap" and it is likely that other extensions took this method over as well.
This leads to the case that all extensions publish their assets under the hash crc32("assets") which leads to a collision.
I don't know what the initial motiviation it was to put this parameter on true but if it doesnt serve any real need it should be set on false in order to prevent such a collision.

**Comment by MeiSign** [comment]
That is a very good advice. I changed it to false. Thank you Michael!
